# Site settings
author: Lukasz Kowalik
title:  A journey of a thousand codes begins with a single click!â€ 
header-img: img/home-bg.png
email: kowalix007@gmail.com
copyright_name: Lukasz Kowalik
description: > # this means to ignore newlines until "baseurl:"
  Online marketer's journey to becoming a software developer
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kowalix-pl

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
